In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
parent_dir = "/home/connorlab/Documents/GitHub/Julie/social_data/zombies_social_data/"
# Load data
aff_df = pd.read_excel(parent_dir + "zombies_feature_df_affiliation.xlsx", index_col=0)
sub_df = pd.read_excel(parent_dir + "zombies_feature_df_submission.xlsx", index_col=0)
ago_df = pd.read_excel(parent_dir + "zombies_feature_df_agonism.xlsx", index_col=0)
# 함수: "Behavior Towards 94B" → "94B"
def clean_col(colname):
    return colname.split()[-1]  # 마지막 단어만 추출

# 컬럼 이름 정리
aff_df.columns = [clean_col(c) for c in aff_df.columns]
sub_df.columns = [clean_col(c) for c in sub_df.columns]
ago_df.columns = [clean_col(c) for c in ago_df.columns]


# 공통 monkey 추출
monkeys = aff_df.index.intersection(sub_df.index).intersection(ago_df.index)
aff = np.array(aff_df)
ago = np.array(ago_df)
sub = np.array(sub_df)

In [3]:
X = aff
X

array([[ 0, 19,  9, 38, 84, 27, 13, 14,  4,  9],
       [15,  0,  9, 41,  4, 13, 19, 71, 12,  0],
       [18, 10,  0, 21,  7, 17, 49, 18,  3,  1],
       [38, 43, 24,  0, 18,  6, 31, 26, 29,  4],
       [90,  3,  8,  8,  0, 22,  8,  9,  1, 18],
       [23, 12, 17,  1, 23,  0, 23, 16,  3, 10],
       [17, 18, 43, 34, 10, 23,  0, 34,  2,  9],
       [11, 70, 18, 17,  8, 17, 33,  0,  5,  3],
       [ 3,  6,  4, 31,  2,  1,  2,  4,  0,  9],
       [ 8,  0,  0,  1, 26,  8,  2,  1,  7,  0]])

In [4]:
from analyses.spike_rate import compute_mean_spike_rate_for_windows
from analyses.enums.monkey_names import get_monkeys_by_default_order
import pandas as pd
monkey_group = "Zombies"
subject_monkey_index = 6
monkey_list = get_monkeys_by_default_order(monkey_group)
sig_windows = pd.read_pickle(
        f'/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/{monkey_group}_significant_windows_pANOVAorGLM_passed.pkl')
ed_sig_windows = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/Ed and ANOVA/used_for_R01/R01_ed_list_duplicate_removed_without_full_window.pkl')
mean_spike_rate_windows = compute_mean_spike_rate_for_windows(ed_sig_windows)

Computing windowed mean spike rate: 100%|██████████| 57/57 [00:01<00:00, 46.88it/s]

In [5]:
spike_rate = mean_spike_rate_windows[mean_spike_rate_windows['MonkeyGroup']=='Zombies']
spike_rate = spike_rate[spike_rate['MonkeyName']!='NewMonkey']
# spike_rate = spike_rate[spike_rate['MonkeyName']!='7124']
spike_rate['MonkeyName'].unique()

array(['110E', '143H', '151J', '67G', '69X', '7124', '72X', '87J', '94B'],
      dtype=object)

In [6]:
X_df = pd.DataFrame(X, index=monkey_list, columns=[f'Feature{i+1}' for i in range(X.shape[1])])

In [7]:
X_df_clean = X_df.drop(index="81G")
X_df_clean

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10
7124,0,19,9,38,84,27,13,14,4,9
69X,15,0,9,41,4,13,19,71,12,0
72X,18,10,0,21,7,17,49,18,3,1
94B,38,43,24,0,18,6,31,26,29,4
110E,90,3,8,8,0,22,8,9,1,18
67G,23,12,17,1,23,0,23,16,3,10
143H,11,70,18,17,8,17,33,0,5,3
87J,3,6,4,31,2,1,2,4,0,9
151J,8,0,0,1,26,8,2,1,7,0

In [8]:
from analyses.linear_regression.multiple_linear_regression import run_lasso_regression

results_df = run_lasso_regression(spike_rate, X_df_clean)
results_df

Running Lasso regressions: 100%|██████████| 57/57 [00:00<00:00, 708.30it/s]

,NeuronID,WindowStart_ms,WindowEnd_ms,R_squared,coefficients,intercept
0,AMG_2023-09-26_1_Channel.C_027_Unit 1,0.0,300.0,0.607786,"[-0.0, 0.0, 0.0, 2.324664222147351, 0.71848530...",29.019400
1,AMG_2023-09-26_2_Channel.C_011_Unit 1,700.0,1000.0,0.000000,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",1.267490
2,AMG_2023-09-26_2_Channel.C_020,50.0,150.0,0.035601,"[0.0, 0.1758495253372199, 0.0, -0.0, -0.0, 0.0...",8.432099
3,AMG_2023-09-26_3_Channel.C_007_Unit 2,100.0,200.0,0.000000,"[-0.0, -0.0, -0.0, 0.0, 0.0, -0.0, -0.0, -0.0,...",0.604938
4,AMG_2023-09-26_3_Channel.C_027_Unit 2,150.0,350.0,0.576757,"[0.7371736612228533, -0.0, -1.1149835063740567...",36.856481
5,AMG_2023-10-03_3_Channel.C_006_Unit 1,200.0,400.0,0.820206,"[-0.0, 0.0, 0.0, 0.7883865679479027, 1.9144310...",9.913580
6,AMG_2023-10-03_3_Channel.C_006_Unit 1,2150.0,2250.0,0.914466,"[-0.0, 0.8267049369410303, 0.0, 2.097501425054...",10.197531
7,AMG_2023-10-03_3_Channel.C_013_Unit 1,200.0,600.0,0.469689,"[0.0, 0.0, 0.0, -0.0, -0.0, -0.684948474591745...",6.731481
8,AMG_2023-10-03_3_Channel.C_026_Unit 1,1900.0,2000.0,0.320441,"[0.0, -0.0, 0.2950846271754267, -0.37979962253...",2.037037
9,AMG_2023-10-03_4_Channel.C_006,450.0,650.0,0.481220,"[-0.0, -0.2979728742207649, -0.0, 0.3207510006...",10.135802
10,AMG_2023-10-03_4_Channel.C_010_Unit 2,200.0,600.0,0.331258,"[-0.0, -0.0, -0.0, 0.015692266795822564, 0.0, ...",1.700617
11,AMG_2023-10-03_4_Channel.C_026,1000.0,1100.0,0.627220,"[0.4055647828247252, -0.0, -0.0, 0.0, -0.0, 0....",2.012346
12,AMG_2023-10-04_1_Channel.C_004_Unit 1,150.0,400.0,0.644330,"[0.1285628405421699, -0.755825813061624, -0.70...",11.866667
13,AMG_2023-10-04_1_Channel.C_019_Unit 3,150.0,400.0,0.704400,"[0.0, -1.1715835594357507, -0.0, -0.0, 0.66623...",15.022222
14,AMG_2023-10-04_2_Channel.C_018_Unit 1,150.0,500.0,0.603308,"[-0.0, 0.0, -0.5221398534414083, 0.0, 0.0, 0.4...",7.936508
15,AMG_2023-10-04_3_Channel.C_002_Unit 1,150.0,400.0,0.745647,"[-0.0, -0.0, -1.7644758723126266, 0.0, 1.96912...",10.661728
16,AMG_2023-10-04_3_Channel.C_004_Unit 2,100.0,500.0,0.810140,"[3.0528560678587287, -0.0, 0.0, -0.0, 0.0, 1.0...",21.188272
17,AMG_2023-10-04_3_Channel.C_009_Unit 1,150.0,500.0,0.903016,"[0.0, 1.1994584389197382, 0.3036556443159132, ...",48.550265
18,AMG_2023-10-04_3_Channel.C_009_Unit 3,100.0,450.0,0.840053,"[2.594526905185888, -0.0, -0.0, -0.0, -0.0, 0....",22.744268
19,AMG_2023-10-04_4_Channel.C_021_Unit 2,150.0,450.0,0.190279,"[0.0, -0.0, 0.0, 0.0, 0.3891316873204156, 0.0,...",12.962963
20,AMG_2023-10-04_4_Channel.C_022_Unit 2,150.0,650.0,0.852153,"[0.7345011719202142, 0.24460396492405673, 0.28...",35.377778
21,AMG_2023-10-04_4_Channel.C_027_Unit 1,350.0,650.0,0.638176,"[0.0, -0.0, 0.0, -0.8107417707699979, 0.0, -0....",6.222222
22,AMG_2023-10-05_1_Channel.C_004_Unit 1,1000.0,1100.0,0.093318,"[-0.0, 0.0, -0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0...",1.481481
23,AMG_2023-10-05_2_Channel.C_009_Unit 1,500.0,850.0,0.000000,"[-0.0, 0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -...",1.523810
24,AMG_2023-10-05_2_Channel.C_018_Unit 1,50.0,350.0,0.000000,"[-0.0, -0.0, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0...",3.962963
25,AMG_2023-10-05_2_Channel.C_019_Unit 2,2200.0,2300.0,0.000000,"[-0.0, -0.0, -0.0, 0.0, -0.0, -0.0, -0.0, 0.0,...",0.555556
26,AMG_2023-10-09_3_Channel.C_013,600.0,750.0,0.364827,"[0.4904445419665095, -0.0, -0.0, -0.0, -0.0, -...",3.185185
27,AMG_2023-10-10_2_Channel.C_007,1150.0,1250.0,0.106910,"[-0.0, 0.0, 0.0, -0.0, -0.0, -0.04825634264737...",2.777778
28,AMG_2023-10-10_2_Channel.C_011,400.0,600.0,0.839059,"[0.0, 0.0, 2.6747299947680534, 0.0, 2.70790806...",9.333333
29,AMG_2023-10-10_2_Channel.C_021,300.0,550.0,0.182323,"[0.0, -0.0, 0.0, -0.0, 0.11520291842315362, 0....",4.088889
30,AMG_2023-10-10_2_Channel.C_021,1550.0,1650.0,0.397880,"[0.0, -0.0, -0.0, 0.0, -0.5201996649372453, -0...",3.111111
31,AMG_2023-10-11_1_Channel.C_002,100.0,500.0,0.376923,"[0.0, -0.0, -0.0, 0.0, 0.5665640946303268, 0.0...",2.083333
32,AMG_2023-10-11_1_Channel.C_010,2000.0,2200.0,0.809779,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.80...",15.388889
33,AMG_2023-10-11_3_Channel.C_013,1650.0,1800.0,0.754497,"[0.0, -2.5153746830292034, 0.0, -0.0, 0.0, -0....",10.088477
34,ER_2023-10-24_2_Channel.C_002,250.0,750.0,0.668757,"[0.0, 0.0, 0.0, -2.155769374352591, -0.0, -0.0...",15.844444
35,ER_2023-10-27_3_Channel.C_007,1750.0,1900.0,0.626739,"[-0.0, -0.0, -0.0, 0.021356605118305325, 1.441...",2.592593
36,ER_2023-10-27_3_Channel.C_013,1600.0,1900.0,0.356104,"[0.0, 0.0, 0.7482823145878179, 0.0, -0.9668140...",11.444444
37,ER_2023-10-27_4_Channel.C_011,200.0,700.0,0.646156,"[0.0, -0.0, -4.267716300595896, 0.120799759034...",54.590123
38,ER_2023-10-27_4_Channel.C_020,200.0,650.0,0.479414,"[0.0, -0.0, -2.751577543473965, 0.0, 0.5250250...",49.458162
39,ER_2023-11-20_1_Channel.C_013,850.0,950.0,0.364722,"[0.0, 0.0, 0.0, -0.0, 0.0, -0.0, 0.0, -0.0, 0....",1.333333
40,ER_2023-11-20_2_Channel.C_006,2200.0,2300.0,0.126621,"[-0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.1292...",0.777778
41,ER_2023-11-25_1_Channel.C_014,1500.0,1600.0,0.565946,"[0.5748324040181119, -0.0, -1.8151881160901813...",14.111111
42,ER_2023-11-25_1_Channel.C_019,100.0,500.0,0.107679,"[0.10208755931970931, 0.0, 0.0, -0.0, -0.0, -0...",6.611111
43,ER_2023-11-25_3_Channel.C_018,50.0,150.0,0.670312,"[2.470810367871459, 0.0, 0.0, -0.0, -0.4491015...",7.735450
44,ER_2023-11-28_3_Channel.C_007,700.0,850.0,0.606259,"[-0.9705355595363743, 0.2058321430958671, 0.0,...",13.629630
45,ER_2023-11-28_4_Channel.C_015,350.0,500.0,0.642317,"[-0.0, 0.5435093754854349, 0.0, 0.273713067084...",16.370370
46,ER_2023-12-05_4_Channel.C_015,650.0,750.0,0.691090,"[0.768378647406272, 0.0, 0.0, -0.5249440202210...",13.888889
47,ER_2023-12-14_1_Channel.C_008,900.0,1050.0,0.547090,"[-0.4432914131338396, -0.0, 2.031757520118538,...",15.991770
48,ER_2023-12-14_1_Channel.C_024,1450.0,1750.0,0.544655,"[-0.0, 2.0349710926606166, -0.0, 0.0, -0.21141...",4.349794
49,ER_2023-12-14_4_Channel.C_006,1900.0,2000.0,0.857379,"[1.8778795903732137, -0.0, 0.01814594099476786...",7.555556
50,ER_2023-12-14_4_Channel.C_008,750.0,850.0,0.856868,"[3.767461767797486, 0.0, -0.8660388101051999, ...",14.888889
51,ER_2023-12-18_2_Channel.C_012_Unit 2,200.0,350.0,0.059845,"[0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0....",0.666667
52,ER_2023-12-18_3_Channel.C_015_Unit 1,2000.0,2150.0,0.278111,"[-0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.67716170...",5.555556
53,ER_2023-12-18_3_Channel.C_020_Unit 1,150.0,400.0,0.497152,"[-0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.7...",1.866667
54,Unknown_2023-10-31_1_Channel.C_005,250.0,600.0,0.577375,"[0.0, -0.0, -0.0, 0.0, -0.0, 0.0, -0.0, -0.0, ...",8.253968
55,Unknown_2023-10-31_1_Channel.C_020,100.0,600.0,0.503460,"[0.0, -0.0, -0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0...",9.133333
56,Unknown_2023-11-08_1_Channel.C_007,100.0,700.0,0.620303,"[0.0, 0.0, 0.0, -0.0, 0.9278800225066729, 0.0,...",6.148148

In [9]:
results_df['NeuronWindowID']= (
    results_df['NeuronID'] + " (" 
    + results_df['WindowStart_ms'].astype(str) + ","
    + results_df['WindowEnd_ms'].astype(str) + ")"
)
sig_results_df = results_df[results_df['R_squared']>0.6]

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Extract the coefficients column as a new DataFrame
coeff_df = pd.DataFrame(results_df['coefficients'].tolist(),
                        index=results_df['NeuronWindowID']) 

filtered_monkey_list = [m for m in monkey_list if m not in ["81G"]]
coeff_df.columns = monkey_list

plt.figure(figsize=(12, 10))
ax = sns.heatmap(coeff_df, cmap='coolwarm', center=0, annot=True, fmt=".1f",
                 yticklabels=True, cbar=True)



# Adjust label fonts AFTER the heatmap has rendered
ax.set_yticklabels(ax.get_yticklabels(), fontsize=7, rotation=0)

# Fix for misalignment: force re-draw with tight layout
plt.tight_layout()
plt.title("Heatmap of Regression Coefficients per Neuron", fontsize=14)
plt.xlabel("Affiliation From")
plt.ylabel("Neuron ID")
plt.show()

In [35]:
sig_coeff_df = pd.DataFrame(sig_results_df['coefficients'].tolist(),
                        index=sig_results_df['NeuronWindowID']) 
sparse_df = sig_coeff_df.replace(0, float('nan'))  # Optional: or use a threshold like < 1e-5
sparse_df.columns = monkey_list
plt.figure(figsize=(12, 10))
ax = sns.heatmap(sparse_df, cmap='coolwarm', center=0, annot=True, fmt=".1f",
                 yticklabels=True, cbar=True)

ax.set_yticklabels(ax.get_yticklabels(), fontsize=7, rotation=0)
plt.tight_layout()
plt.title("Sparse Heatmap of Lasso Coefficients (Non-zero only)", fontsize=14)
plt.xlabel("Affiliation From")
plt.ylabel("Neuron ID")
plt.show()

In [31]:
selection_counts = (coeff_df != 0).sum(axis=0).sort_values(ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=selection_counts.values, y=selection_counts.index)
plt.title("Number of Neurons Selecting Each Feature (Non-zero Coefficients)")
plt.xlabel("Count")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

# Ridge Regression

In [15]:
from analyses.linear_regression.multiple_linear_regression import run_ridge_regression

ridge_results_df = run_ridge_regression(spike_rate, X_df_clean)
ridge_results_df['NeuronWindowID']= (
    ridge_results_df['NeuronID'] + " (" 
    + ridge_results_df['WindowStart_ms'].astype(str) + ","
    + ridge_results_df['WindowEnd_ms'].astype(str) + ")"
)

Running Ridge regressions: 100%|██████████| 57/57 [00:00<00:00, 571.34it/s]

In [16]:
ridge_results_df

,NeuronID,WindowStart_ms,WindowEnd_ms,R_squared,coefficients,intercept,NeuronWindowID
0,AMG_2023-09-26_1_Channel.C_027_Unit 1,0.0,300.0,0.875254,"[-0.06781398566541427, -0.003084432468187736, ...",29.019400,"AMG_2023-09-26_1_Channel.C_027_Unit 1 (0.0,300.0)"
1,AMG_2023-09-26_2_Channel.C_011_Unit 1,700.0,1000.0,0.963928,"[-0.18601646459909532, 0.3082281323990709, 0.4...",1.267490,"AMG_2023-09-26_2_Channel.C_011_Unit 1 (700.0,1..."
2,AMG_2023-09-26_2_Channel.C_020,50.0,150.0,0.838477,"[0.005598756926974643, 1.0898215137993839, 1.2...",8.432099,"AMG_2023-09-26_2_Channel.C_020 (50.0,150.0)"
3,AMG_2023-09-26_3_Channel.C_007_Unit 2,100.0,200.0,0.945654,"[-0.32693161539069754, -0.05497374601627148, -...",0.604938,"AMG_2023-09-26_3_Channel.C_007_Unit 2 (100.0,2..."
4,AMG_2023-09-26_3_Channel.C_027_Unit 2,150.0,350.0,0.967803,"[1.745700619454517, -0.597026489478909, -2.492...",36.856481,"AMG_2023-09-26_3_Channel.C_027_Unit 2 (150.0,3..."
5,AMG_2023-10-03_3_Channel.C_006_Unit 1,200.0,400.0,0.990491,"[-0.5104971169640244, -0.1723066851729899, 0.1...",9.913580,"AMG_2023-10-03_3_Channel.C_006_Unit 1 (200.0,4..."
6,AMG_2023-10-03_3_Channel.C_006_Unit 1,2150.0,2250.0,0.995632,"[-1.403561053763676, 1.0181006752015505, 0.937...",10.197531,"AMG_2023-10-03_3_Channel.C_006_Unit 1 (2150.0,..."
7,AMG_2023-10-03_3_Channel.C_013_Unit 1,200.0,600.0,0.964785,"[-0.0731699513694563, 0.0063494147810406075, -...",6.731481,"AMG_2023-10-03_3_Channel.C_013_Unit 1 (200.0,6..."
8,AMG_2023-10-03_3_Channel.C_026_Unit 1,1900.0,2000.0,0.940384,"[0.020704795472855142, -0.9977723310688308, 1....",2.037037,"AMG_2023-10-03_3_Channel.C_026_Unit 1 (1900.0,..."
9,AMG_2023-10-03_4_Channel.C_006,450.0,650.0,0.953206,"[-0.5683744042572053, -1.2900515654143103, 0.3...",10.135802,"AMG_2023-10-03_4_Channel.C_006 (450.0,650.0)"
10,AMG_2023-10-03_4_Channel.C_010_Unit 2,200.0,600.0,0.995269,"[0.08591319521519512, -0.1676994449009067, -0....",1.700617,"AMG_2023-10-03_4_Channel.C_010_Unit 2 (200.0,6..."
11,AMG_2023-10-03_4_Channel.C_026,1000.0,1100.0,0.991018,"[1.0596499721247203, -0.14051790396483108, -0....",2.012346,"AMG_2023-10-03_4_Channel.C_026 (1000.0,1100.0)"
12,AMG_2023-10-04_1_Channel.C_004_Unit 1,150.0,400.0,0.945578,"[1.0760144776292881, -1.899282631026795, -2.10...",11.866667,"AMG_2023-10-04_1_Channel.C_004_Unit 1 (150.0,4..."
13,AMG_2023-10-04_1_Channel.C_019_Unit 3,150.0,400.0,0.938116,"[0.855143027923463, -2.2329088290220374, -1.21...",15.022222,"AMG_2023-10-04_1_Channel.C_019_Unit 3 (150.0,4..."
14,AMG_2023-10-04_2_Channel.C_018_Unit 1,150.0,500.0,0.955962,"[-0.200607429363912, -0.2189249942623278, -1.3...",7.936508,"AMG_2023-10-04_2_Channel.C_018_Unit 1 (150.0,5..."
15,AMG_2023-10-04_3_Channel.C_002_Unit 1,150.0,400.0,0.955510,"[-0.5084562590139842, -1.5116373699003443, -1....",10.661728,"AMG_2023-10-04_3_Channel.C_002_Unit 1 (150.0,4..."
16,AMG_2023-10-04_3_Channel.C_004_Unit 2,100.0,500.0,0.988354,"[2.5968229378325067, -1.2942776765618345, 0.92...",21.188272,"AMG_2023-10-04_3_Channel.C_004_Unit 2 (100.0,5..."
17,AMG_2023-10-04_3_Channel.C_009_Unit 1,150.0,500.0,0.987205,"[1.0832353930787424, 0.6313924414983179, 2.483...",48.550265,"AMG_2023-10-04_3_Channel.C_009_Unit 1 (150.0,5..."
18,AMG_2023-10-04_3_Channel.C_009_Unit 3,100.0,450.0,0.983359,"[1.85754002708075, -0.10100401720980395, 0.163...",22.744268,"AMG_2023-10-04_3_Channel.C_009_Unit 3 (100.0,4..."
19,AMG_2023-10-04_4_Channel.C_021_Unit 2,150.0,450.0,0.934285,"[0.0473307961246954, -0.6784517412474304, 1.36...",12.962963,"AMG_2023-10-04_4_Channel.C_021_Unit 2 (150.0,4..."
20,AMG_2023-10-04_4_Channel.C_022_Unit 2,150.0,650.0,0.956127,"[1.1012768984229564, 0.7441536550064213, -0.16...",35.377778,"AMG_2023-10-04_4_Channel.C_022_Unit 2 (150.0,6..."
21,AMG_2023-10-04_4_Channel.C_027_Unit 1,350.0,650.0,0.969770,"[0.7144302472700683, -0.7365641821321646, 0.04...",6.222222,"AMG_2023-10-04_4_Channel.C_027_Unit 1 (350.0,6..."
22,AMG_2023-10-05_1_Channel.C_004_Unit 1,1000.0,1100.0,0.893499,"[-0.21896688300873227, 0.4651969134047922, 0.2...",1.481481,"AMG_2023-10-05_1_Channel.C_004_Unit 1 (1000.0,..."
23,AMG_2023-10-05_2_Channel.C_009_Unit 1,500.0,850.0,0.980654,"[-0.34934661446072246, 0.5674528621329804, -0....",1.523810,"AMG_2023-10-05_2_Channel.C_009_Unit 1 (500.0,8..."
24,AMG_2023-10-05_2_Channel.C_018_Unit 1,50.0,350.0,0.931648,"[-0.11696055024127738, -0.5407326530480835, 0....",3.962963,"AMG_2023-10-05_2_Channel.C_018_Unit 1 (50.0,35..."
25,AMG_2023-10-05_2_Channel.C_019_Unit 2,2200.0,2300.0,0.940959,"[-0.24923877544652656, 0.006250644440077203, -...",0.555556,"AMG_2023-10-05_2_Channel.C_019_Unit 2 (2200.0,..."
26,AMG_2023-10-09_3_Channel.C_013,600.0,750.0,0.943806,"[0.8524805189365784, -0.2748471567702992, -0.5...",3.185185,"AMG_2023-10-09_3_Channel.C_013 (600.0,750.0)"
27,AMG_2023-10-10_2_Channel.C_007,1150.0,1250.0,0.913910,"[-0.4480597152660474, -0.4278952919022313, 1.5...",2.777778,"AMG_2023-10-10_2_Channel.C_007 (1150.0,1250.0)"
28,AMG_2023-10-10_2_Channel.C_011,400.0,600.0,0.978593,"[-0.36501829613133185, 0.8062739270104523, 1.9...",9.333333,"AMG_2023-10-10_2_Channel.C_011 (400.0,600.0)"
29,AMG_2023-10-10_2_Channel.C_021,300.0,550.0,0.942919,"[-0.16183824691079218, -0.5103708087278519, 0....",4.088889,"AMG_2023-10-10_2_Channel.C_021 (300.0,550.0)"
30,AMG_2023-10-10_2_Channel.C_021,1550.0,1650.0,0.983776,"[0.21178691977340602, -0.04188510236575462, 0....",3.111111,"AMG_2023-10-10_2_Channel.C_021 (1550.0,1650.0)"
31,AMG_2023-10-11_1_Channel.C_002,100.0,500.0,0.974717,"[-0.05655374125343752, -0.020821581011361487, ...",2.083333,"AMG_2023-10-11_1_Channel.C_002 (100.0,500.0)"
32,AMG_2023-10-11_1_Channel.C_010,2000.0,2200.0,0.964539,"[0.2939817244110664, 0.2656844190463062, 0.404...",15.388889,"AMG_2023-10-11_1_Channel.C_010 (2000.0,2200.0)"
33,AMG_2023-10-11_3_Channel.C_013,1650.0,1800.0,0.956715,"[-0.03312602448408339, -2.914245199995669, -0....",10.088477,"AMG_2023-10-11_3_Channel.C_013 (1650.0,1800.0)"
34,ER_2023-10-24_2_Channel.C_002,250.0,750.0,0.940157,"[0.3722240710928491, 0.2638403403076116, 1.279...",15.844444,"ER_2023-10-24_2_Channel.C_002 (250.0,750.0)"
35,ER_2023-10-27_3_Channel.C_007,1750.0,1900.0,0.982570,"[-0.6654128505934214, -0.36569319245644044, 0....",2.592593,"ER_2023-10-27_3_Channel.C_007 (1750.0,1900.0)"
36,ER_2023-10-27_3_Channel.C_013,1600.0,1900.0,0.965233,"[0.17395672394321116, 0.8204511882224457, 1.80...",11.444444,"ER_2023-10-27_3_Channel.C_013 (1600.0,1900.0)"
37,ER_2023-10-27_4_Channel.C_011,200.0,700.0,0.900961,"[0.46250539010120784, -1.8948417653427525, -4....",54.590123,"ER_2023-10-27_4_Channel.C_011 (200.0,700.0)"
38,ER_2023-10-27_4_Channel.C_020,200.0,650.0,0.888624,"[0.5750632820264858, -1.8306568768222085, -3.7...",49.458162,"ER_2023-10-27_4_Channel.C_020 (200.0,650.0)"
39,ER_2023-11-20_1_Channel.C_013,850.0,950.0,0.956086,"[0.19820396928654824, 0.15557279906964663, 0.1...",1.333333,"ER_2023-11-20_1_Channel.C_013 (850.0,950.0)"
40,ER_2023-11-20_2_Channel.C_006,2200.0,2300.0,0.922292,"[-0.12395633143756055, -0.32965774720026975, 0...",0.777778,"ER_2023-11-20_2_Channel.C_006 (2200.0,2300.0)"
41,ER_2023-11-25_1_Channel.C_014,1500.0,1600.0,0.943725,"[0.7401407410945845, -1.6840153053326492, -2.3...",14.111111,"ER_2023-11-25_1_Channel.C_014 (1500.0,1600.0)"
42,ER_2023-11-25_1_Channel.C_019,100.0,500.0,0.869481,"[0.5714263860183998, 0.41456166216720625, -0.8...",6.611111,"ER_2023-11-25_1_Channel.C_019 (100.0,500.0)"
43,ER_2023-11-25_3_Channel.C_018,50.0,150.0,0.959091,"[2.119073521782965, 0.3739396980284113, -1.188...",7.735450,"ER_2023-11-25_3_Channel.C_018 (50.0,150.0)"
44,ER_2023-11-28_3_Channel.C_007,700.0,850.0,0.975819,"[-1.2845542534480077, 0.5375318222955562, 0.75...",13.629630,"ER_2023-11-28_3_Channel.C_007 (700.0,850.0)"
45,ER_2023-11-28_4_Channel.C_015,350.0,500.0,0.983179,"[0.011793063354633497, 1.1567583495394385, 0.1...",16.370370,"ER_2023-11-28_4_Channel.C_015 (350.0,500.0)"
46,ER_2023-12-05_4_Channel.C_015,650.0,750.0,0.926055,"[1.3405822658600364, 0.11648598203385702, -0.5...",13.888889,"ER_2023-12-05_4_Channel.C_015 (650.0,750.0)"
47,ER_2023-12-14_1_Channel.C_008,900.0,1050.0,0.875901,"[-1.75224725161759, -0.26374511038359355, 3.94...",15.991770,"ER_2023-12-14_1_Channel.C_008 (900.0,1050.0)"
48,ER_2023-12-14_1_Channel.C_024,1450.0,1750.0,0.959656,"[-0.7368549970729172, 2.411654418532142, 1.189...",4.349794,"ER_2023-12-14_1_Channel.C_024 (1450.0,1750.0)"
49,ER_2023-12-14_4_Channel.C_006,1900.0,2000.0,0.993829,"[2.5475624072041154, -1.276008257065805, 1.791...",7.555556,"ER_2023-12-14_4_Channel.C_006 (1900.0,2000.0)"
50,ER_2023-12-14_4_Channel.C_008,750.0,850.0,0.969823,"[4.327832388542126, -0.12068087903060572, -1.3...",14.888889,"ER_2023-12-14_4_Channel.C_008 (750.0,850.0)"
51,ER_2023-12-18_2_Channel.C_012_Unit 2,200.0,350.0,0.963126,"[0.11238033411058719, -0.11446977103164817, 0....",0.666667,"ER_2023-12-18_2_Channel.C_012_Unit 2 (200.0,35..."
52,ER_2023-12-18_3_Channel.C_015_Unit 1,2000.0,2150.0,0.920971,"[-0.2619548437676908, -0.6787615273019802, -0....",5.555556,"ER_2023-12-18_3_Channel.C_015_Unit 1 (2000.0,2..."
53,ER_2023-12-18_3_Channel.C_020_Unit 1,150.0,400.0,0.971834,"[0.0027265868644932418, -0.2403430338260093, 0...",1.866667,"ER_2023-12-18_3_Channel.C_020_Unit 1 (150.0,40..."
54,Unknown_2023-10-31_1_Channel.C_005,250.0,600.0,0.989710,"[0.659599851940019, -0.024277198813180526, -0....",8.253968,"Unknown_2023-10-31_1_Channel.C_005 (250.0,600.0)"
55,Unknown_2023-10-31_1_Channel.C_020,100.0,600.0,0.982795,"[0.7517167101517316, -0.3884951603926473, 0.41...",9.133333,"Unknown_2023-10-31_1_Channel.C_020 (100.0,600.0)"
56,Unknown_2023-11-08_1_Channel.C_007,100.0,700.0,0.994886,"[-0.04351450074240746, 0.11228766978780659, 0....",6.148148,"Unknown_2023-11-08_1_Channel.C_007 (100.0,700.0)"

In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Extract the coefficients column as a new DataFrame
coeff_df = pd.DataFrame(ridge_results_df['coefficients'].tolist(),
                        index=ridge_results_df['NeuronWindowID']) 

filtered_monkey_list = [m for m in monkey_list if m not in ["81G"]]
coeff_df.columns = monkey_list

plt.figure(figsize=(12, 10))
ax = sns.heatmap(coeff_df, cmap='coolwarm', center=0, annot=True, fmt=".1f",
                 yticklabels=True, cbar=True)



# Adjust label fonts AFTER the heatmap has rendered
ax.set_yticklabels(ax.get_yticklabels(), fontsize=7, rotation=0)

# Fix for misalignment: force re-draw with tight layout
plt.tight_layout()
plt.title("Heatmap of Regression Coefficients per Neuron", fontsize=14)
plt.xlabel("Affiliation From")
plt.ylabel("Neuron ID")
plt.show()