In [4]:
import pandas as pd

sorted = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/sorted_spike_cache/2023-09-26_round_3.pkl')
sorted

,TaskField,SpikeTimes,Channel,BaseChannel,EpochStartStop,MonkeyGroup,MonkeyId,MonkeyName,Date,Round No.,Location
0,1695753698845000,[],Channel.C_021_Unit 1,Channel.C_021,"(3.9929, 6.5124)",Stranger Things,2854,40J,2023-09-26,3,AMG
1,1695753698845000,"[4.1645, 4.25195, 4.33145, 4.43535, 4.47, 4.47...",Channel.C_005_Unit 1,Channel.C_005,"(3.9929, 6.5124)",Stranger Things,2854,40J,2023-09-26,3,AMG
2,1695753698845000,"[4.92265, 5.3978, 5.7143]",Channel.C_011_Unit 1,Channel.C_011,"(3.9929, 6.5124)",Stranger Things,2854,40J,2023-09-26,3,AMG
3,1695753698845000,"[4.41655, 4.8451, 6.3402]",Channel.C_004_Unit 1,Channel.C_004,"(3.9929, 6.5124)",Stranger Things,2854,40J,2023-09-26,3,AMG
4,1695753698845000,"[4.0812, 4.26945, 6.19865, 6.41265]",Channel.C_005_Unit 2,Channel.C_005,"(3.9929, 6.5124)",Stranger Things,2854,40J,2023-09-26,3,AMG
...,...,...,...,...,...,...,...,...,...,...,...
3375,1695753725090000,[],Channel.C_010_Unit 1,Channel.C_010,"(1739.8702, 1740.1782)",Instigators,1723,42Z,2023-09-26,3,AMG
3376,1695753725090000,"[1739.93195, 1739.941, 1739.9623, 1740.0005, 1...",Channel.C_017_Unit 1,Channel.C_017,"(1739.8702, 1740.1782)",Instigators,1723,42Z,2023-09-26,3,AMG
3377,1695753725090000,[],Channel.C_006_Unit 1,Channel.C_006,"(1739.8702, 1740.1782)",Instigators,1723,42Z,2023-09-26,3,AMG
3378,1695753725090000,[],Channel.C_010_Unit 2,Channel.C_010,"(1739.8702, 1740.1782)",Instigators,1723,42Z,2023-09-26,3,AMG
3379,1695753725090000,[],Channel.C_005_Unit 3,Channel.C_005,"(1739.8702, 1740.1782)",Instigators,1723,42Z,2023-09-26,3,AMG

In [5]:
unsorted = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/exploded_spike_cache/2023-09-26_round_3.pkl')
unsorted

,TaskField,MonkeyId,MonkeyGroup,MonkeyName,Channel,SpikeTimes,EpochStartStop,BaseChannel,Date,Round No.,Location,NeuronID
0,1695753698845000,2854,Stranger Things,40J,Channel.C_012_Unit 1,[],"(3.9929, 6.5124)",Channel.C_012,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_012_Unit 1
1,1695753698845000,2854,Stranger Things,40J,Channel.C_012_Unit 2,[],"(3.9929, 6.5124)",Channel.C_012,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_012_Unit 2
2,1695753698845000,2854,Stranger Things,40J,Channel.C_027_Unit 1,"[4.4698, 4.4734, 4.6099, 4.61325, 4.62355, 4.6...","(3.9929, 6.5124)",Channel.C_027,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_027_Unit 1
3,1695753698845000,2854,Stranger Things,40J,Channel.C_027_Unit 2,"[3.99515, 4.0247, 4.05085, 4.05665, 4.08425, 4...","(3.9929, 6.5124)",Channel.C_027,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_027_Unit 2
4,1695753698845000,2854,Stranger Things,40J,Channel.C_027_Unit 3,"[4.0088, 4.01415, 4.02375, 4.03355, 4.04005, 4...","(3.9929, 6.5124)",Channel.C_027,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_027_Unit 3
...,...,...,...,...,...,...,...,...,...,...,...,...
10803,1695753725090000,1723,Instigators,42Z,Channel.C_004,"[8.32005, 8.3231, 8.3273, 8.6976, 8.70055, 8.7...","(8.1331, 10.70825)",Channel.C_004,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_004
10804,1695753725090000,1723,Instigators,42Z,Channel.C_005,[],"(8.1331, 10.70825)",Channel.C_005,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_005
10805,1695753725090000,1723,Instigators,42Z,Channel.C_006,"[8.17455, 8.1865, 8.9367]","(8.1331, 10.70825)",Channel.C_006,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_006
10808,1695753725090000,1723,Instigators,42Z,Channel.C_013,"[8.16855, 8.17335, 8.26025, 8.2657, 8.41085, 8...","(8.1331, 10.70825)",Channel.C_013,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_013
10812,1695753725090000,1723,Instigators,42Z,Channel.C_025,"[8.17455, 8.1866, 8.93675, 9.7021, 9.70555, 9....","(8.1331, 10.70825)",Channel.C_025,2023-09-26,3,AMG,AMG_2023-09-26_3_Channel.C_025