In [4]:
import pandas as pd
neur = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_sorted_neurons_pKW_passed.pkl')
neur

                                 NeuronID  H-statistic   p-value
0   AMG_2023-09-26_2_Channel.C_018_Unit 1    16.385346  0.023976
1   AMG_2023-09-29_3_Channel.C_017_Unit 1    16.497641  0.024975
2   AMG_2023-10-03_3_Channel.C_016_Unit 1    18.263594  0.014985
3   AMG_2023-10-03_4_Channel.C_005_Unit 1    16.033746  0.026973
4   AMG_2023-10-04_2_Channel.C_012_Unit 2    16.133845  0.030969
5   AMG_2023-10-04_2_Channel.C_022_Unit 1    17.125669  0.019980
6   AMG_2023-10-04_4_Channel.C_000_Unit 1    31.520459  0.000999
7   AMG_2023-10-04_4_Channel.C_018_Unit 1    15.288940  0.047952
8   AMG_2023-10-10_2_Channel.C_002_Unit 1    17.258376  0.033966
9   AMG_2023-10-10_2_Channel.C_012_Unit 1    15.254605  0.048951
10  AMG_2023-10-10_2_Channel.C_015_Unit 1    17.946285  0.016983
11   ER_2023-11-08_4_Channel.C_019_Unit 1    15.348379  0.034965
12   ER_2023-11-20_2_Channel.C_026_Unit 1    20.113949  0.008991
13   ER_2023-11-22_2_Channel.C_013_Unit 1    16.363773  0.028971
14   ER_2023-11-22_3_Channel.C_010_Unit 1    18.177808  0.019980
15   ER_2023-11-22_4_Channel.C_016_Unit 3    16.526490  0.035964
16   ER_2023-11-28_4_Channel.C_030_Unit 1    15.104491  0.049950
17   ER_2023-12-11_3_Channel.C_022_Unit 1    17.445648  0.012987
18   ER_2023-12-18_3_Channel.C_004_Unit 1    16.711872  0.036963
19   ER_2023-12-18_3_Channel.C_023_Unit 1    15.538326  0.041958

In [8]:
original_neu = pd.read_pickle('/old/old_analysis_cache/Zombies_significant_neurons_pANOVAorGLM_passed.pkl')
original = original_neu[original_neu['PermANOVA_p-value']<0.05]
original.shape

(30, 8)

In [7]:
compare = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/mixed_manual_Zombies_significant_neurons_pANOVA_passed.pkl')
compare.shape

(32, 3)

In [11]:
original['NeuronID'].str.contains('Unkn').sum()

4

In [15]:
df1 = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_windows_KW_passed.pkl')
df2 = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_windows_pKW_passed.pkl')

In [17]:
overlap = set(df1['NeuronID']) & set(df2['NeuronID'])
len(overlap)

37

In [19]:
only_in_df1 = set(df1['NeuronID']) - set(df2['NeuronID'])
only_in_df1

set()

In [21]:
only_in_df2 = set(df2['NeuronID']) - set(df1['NeuronID'])
only_in_df2

{'AMG_2023-10-11_3_Channel.C_013'}

In [22]:
donkey = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/sorted_units_Zombies_response_windows.pkl')
donkey

                                      NeuronID WindowStart_ms WindowEnd_ms
0        AMG_2023-09-26_2_Channel.C_000_Unit 1            650          750
1        AMG_2023-09-26_2_Channel.C_000_Unit 1           1000         1250
2        AMG_2023-09-26_2_Channel.C_000_Unit 2            200          450
3        AMG_2023-09-26_2_Channel.C_000_Unit 2           2050         2200
4        AMG_2023-09-26_2_Channel.C_008_Unit 1            250          350
..                                         ...            ...          ...
307  Unknown_2023-11-08_2_Channel.C_017_Unit 1           1400         1500
308  Unknown_2023-11-08_2_Channel.C_019_Unit 2            200          400
309  Unknown_2023-11-08_2_Channel.C_019_Unit 2           1400         1500
311  Unknown_2023-11-08_3_Channel.C_015_Unit 1            800          900
310  Unknown_2023-11-08_3_Channel.C_015_Unit 1            200          400

[523 rows x 3 columns]

In [23]:
si_sorted_windows = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/si_sorted_Zombies_response_windows.pkl')
original_windows = pd.read_pickle('/old/old_analysis_cache/Zombies_response_windows.pkl')
si_sorted_windows.shape

(523, 3)

In [24]:
original_windows.shape

(735, 3)

In [25]:
marine = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_windows_KW_passed.pkl')
marine2 = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/sorted_Zombies_significant_windows_pKW_passed.pkl')

marine.shape

(39, 5)

In [26]:
marine2.shape

(6, 5)

In [6]:
hel = pd.read_pickle('/old/old_analysis_cache/Zombies_significant_windows_pANOVAorGLM_passed.pkl')
hey = hel[hel['PermANOVA_p-value']<0.05]
hey

,NeuronID,GLM_p-value,WindowStart_ms,WindowEnd_ms,F-statistic,PermANOVA_p-value,GLM_pval_corrected,GLM_significant,Permutation_pval_corrected,Permutation_significant
29,AMG_2023-09-26_3_Channel.C_027_Unit 2,4.677418e-83,150,350,2.101942,0.037,6.139111e-82,True,0.715658,False
45,AMG_2023-10-03_1_Channel.C_009,0.000000e+00,150,600,2.001631,0.041,0.000000e+00,True,0.735000,False
54,AMG_2023-10-03_3_Channel.C_006_Unit 1,7.350817e-04,200,400,4.400109,0.000,1.530553e-03,True,0.000000,True
56,AMG_2023-10-03_3_Channel.C_006_Unit 1,7.350817e-04,2150,2250,4.370457,0.002,1.530553e-03,True,0.122500,False
83,AMG_2023-10-03_4_Channel.C_006,2.099579e-02,450,650,2.890313,0.011,2.981866e-02,True,0.459375,False
109,AMG_2023-10-04_1_Channel.C_004_Unit 1,1.522773e-14,150,400,6.857850,0.000,6.217995e-14,True,0.000000,True
116,AMG_2023-10-04_1_Channel.C_019_Unit 3,1.124395e-21,150,400,4.967133,0.000,5.366558e-21,True,0.000000,True
127,AMG_2023-10-04_2_Channel.C_018_Unit 1,2.978656e-05,150,500,12.549542,0.000,7.201685e-05,True,0.000000,True
133,AMG_2023-10-04_3_Channel.C_002_Unit 1,9.487733e-05,150,400,5.019932,0.000,2.158973e-04,True,0.000000,True
134,AMG_2023-10-04_3_Channel.C_004_Unit 2,7.482052e-157,100,500,2.210789,0.042,1.718534e-155,True,0.735000,False
135,AMG_2023-10-04_3_Channel.C_009_Unit 1,0.000000e+00,150,500,3.696778,0.002,0.000000e+00,True,0.122500,False
136,AMG_2023-10-04_3_Channel.C_009_Unit 3,6.366925e-152,100,450,2.161511,0.039,1.418088e-150,True,0.716625,False
153,AMG_2023-10-04_4_Channel.C_021_Unit 2,1.399042e-20,150,450,2.140625,0.032,6.347507e-20,True,0.691765,False
154,AMG_2023-10-04_4_Channel.C_022_Unit 2,1.031696e-298,150,650,3.480455,0.000,4.212760e-297,True,0.000000,True
161,AMG_2023-10-04_4_Channel.C_027_Unit 1,1.936197e-03,350,650,4.469791,0.000,3.825550e-03,True,0.000000,True
167,AMG_2023-10-05_2_Channel.C_009_Unit 1,9.991538e-01,500,850,3.726000,0.000,9.993792e-01,False,0.000000,True
170,AMG_2023-10-05_2_Channel.C_018_Unit 1,1.182792e-02,50,350,2.579143,0.017,1.861568e-02,True,0.499800,False
186,AMG_2023-10-09_3_Channel.C_013,1.372647e-02,600,750,2.493377,0.023,2.080198e-02,True,0.582931,False
196,AMG_2023-10-10_2_Channel.C_007,2.130220e-02,1150,1250,2.276471,0.028,2.981866e-02,True,0.643125,False
203,AMG_2023-10-10_2_Channel.C_011,7.633591e-05,400,600,2.430960,0.022,1.753340e-04,True,0.577500,False
208,AMG_2023-10-10_2_Channel.C_021,2.206084e-02,300,550,2.702228,0.013,2.981866e-02,True,0.459375,False
260,AMG_2023-10-11_3_Channel.C_013,7.737804e-04,1650,1800,3.026091,0.012,1.602052e-03,True,0.459375,False
276,ER_2023-10-27_3_Channel.C_007,7.436401e-03,1750,1900,2.533262,0.015,1.259390e-02,True,0.459375,False
278,ER_2023-10-27_3_Channel.C_013,1.823604e-18,1600,1900,2.059445,0.043,7.931059e-18,True,0.735000,False
306,ER_2023-10-27_4_Channel.C_011,0.000000e+00,200,700,2.948020,0.004,0.000000e+00,True,0.210000,False
312,ER_2023-10-27_4_Channel.C_020,0.000000e+00,200,650,2.888715,0.007,0.000000e+00,True,0.321563,False
422,ER_2023-11-25_1_Channel.C_014,1.823604e-18,1500,1600,2.549832,0.015,7.931059e-18,True,0.459375,False
426,ER_2023-11-25_1_Channel.C_019,1.249300e-13,100,500,2.264352,0.036,4.832818e-13,True,0.715135,False
475,ER_2023-11-28_3_Channel.C_007,1.772966e-09,700,850,2.478462,0.015,5.521793e-09,True,0.459375,False
496,ER_2023-11-28_4_Channel.C_015,9.829624e-09,350,500,2.219731,0.033,2.855642e-08,True,0.693000,False
521,ER_2023-12-05_4_Channel.C_015,8.542064e-23,650,750,2.129610,0.039,4.329943e-22,True,0.716625,False
536,ER_2023-12-07_2_Channel.C_022,8.606813e-04,500,700,1.966875,0.028,1.767041e-03,True,0.643125,False
568,ER_2023-12-14_1_Channel.C_008,2.075725e-04,900,1050,2.170377,0.030,4.651397e-04,True,0.668182,False
575,ER_2023-12-14_1_Channel.C_024,2.727467e-05,1450,1750,5.250529,0.000,6.638041e-05,True,0.000000,True
596,ER_2023-12-14_4_Channel.C_006,4.711620e-11,1900,2000,2.573589,0.013,1.559928e-10,True,0.459375,False
599,ER_2023-12-14_4_Channel.C_008,1.176315e-121,750,850,2.127436,0.022,2.216900e-120,True,0.577500,False
622,ER_2023-12-18_3_Channel.C_015_Unit 1,1.128111e-02,2000,2150,2.180261,0.024,1.786987e-02,True,0.588000,False
631,Unknown_2023-10-31_1_Channel.C_005,6.138158e-24,200,500,3.040777,0.005,3.444011e-23,True,0.245000,False
645,Unknown_2023-10-31_1_Channel.C_020,5.231964e-30,200,500,2.563083,0.015,3.527976e-29,True,0.459375,False
649,Unknown_2023-10-31_1_Channel.C_021,5.145524e-03,2550,2700,2.367967,0.021,9.315265e-03,True,0.577500,False
698,Unknown_2023-11-08_1_Channel.C_005,7.436401e-03,1100,1200,2.206795,0.034,1.259390e-02,True,0.694167,False
699,Unknown_2023-11-08_1_Channel.C_007,2.171399e-04,150,450,5.189820,0.000,4.707901e-04,True,0.000000,True
707,Unknown_2023-11-08_2_Channel.C_015,1.795575e-05,350,500,1.967839,0.047,4.399158e-05,True,0.785114,False

In [15]:
merong = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/mixed_manual_Zombies_response_windows.pkl')
merong2 = pd.read_pickle('/old/old_analysis_cache/Zombies_response_windows.pkl')
merong.shape

(712, 5)

In [16]:
merong2.shape

(735, 3)