In [2]:
import pandas as pd
neur = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_neurons_pKW_passed.pkl')
neur

                                 NeuronID  H-statistic   p-value
0   AMG_2023-09-26_2_Channel.C_018_Unit 1    16.385346  0.023976
1   AMG_2023-09-29_3_Channel.C_017_Unit 1    16.497641  0.024975
2   AMG_2023-10-03_3_Channel.C_016_Unit 1    18.263594  0.014985
3   AMG_2023-10-03_4_Channel.C_005_Unit 1    16.033746  0.026973
4   AMG_2023-10-04_2_Channel.C_012_Unit 2    16.133845  0.030969
5   AMG_2023-10-04_2_Channel.C_022_Unit 1    17.125669  0.019980
6   AMG_2023-10-04_4_Channel.C_000_Unit 1    31.520459  0.000999
7   AMG_2023-10-04_4_Channel.C_018_Unit 1    15.288940  0.047952
8   AMG_2023-10-10_2_Channel.C_002_Unit 1    17.258376  0.033966
9   AMG_2023-10-10_2_Channel.C_012_Unit 1    15.254605  0.048951
10  AMG_2023-10-10_2_Channel.C_015_Unit 1    17.946285  0.016983
11   ER_2023-11-08_4_Channel.C_019_Unit 1    15.348379  0.034965
12   ER_2023-11-20_2_Channel.C_026_Unit 1    20.113949  0.008991
13   ER_2023-11-22_2_Channel.C_013_Unit 1    16.363773  0.028971
14   ER_2023-11-22_3_Channel.C_010_Unit 1    18.177808  0.019980
15   ER_2023-11-22_4_Channel.C_016_Unit 3    16.526490  0.035964
16   ER_2023-11-28_4_Channel.C_030_Unit 1    15.104491  0.049950
17   ER_2023-12-11_3_Channel.C_022_Unit 1    17.445648  0.012987
18   ER_2023-12-18_3_Channel.C_004_Unit 1    16.711872  0.036963
19   ER_2023-12-18_3_Channel.C_023_Unit 1    15.538326  0.041958

In [6]:
original_neu = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_neurons_pANOVAorGLM_passed.pkl')
original = original_neu[original_neu['PermANOVA_p-value']<0.05]

In [11]:
original['NeuronID'].str.contains('Unkn').sum()

4

In [15]:
df1 = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_windows_KW_passed.pkl')
df2 = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_windows_pKW_passed.pkl')

In [17]:
overlap = set(df1['NeuronID']) & set(df2['NeuronID'])
len(overlap)

37

In [19]:
only_in_df1 = set(df1['NeuronID']) - set(df2['NeuronID'])
only_in_df1

set()

In [21]:
only_in_df2 = set(df2['NeuronID']) - set(df1['NeuronID'])
only_in_df2

{'AMG_2023-10-11_3_Channel.C_013'}

In [22]:
donkey = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/sorted_units_Zombies_response_windows.pkl')
donkey

                                      NeuronID WindowStart_ms WindowEnd_ms
0        AMG_2023-09-26_2_Channel.C_000_Unit 1            650          750
1        AMG_2023-09-26_2_Channel.C_000_Unit 1           1000         1250
2        AMG_2023-09-26_2_Channel.C_000_Unit 2            200          450
3        AMG_2023-09-26_2_Channel.C_000_Unit 2           2050         2200
4        AMG_2023-09-26_2_Channel.C_008_Unit 1            250          350
..                                         ...            ...          ...
307  Unknown_2023-11-08_2_Channel.C_017_Unit 1           1400         1500
308  Unknown_2023-11-08_2_Channel.C_019_Unit 2            200          400
309  Unknown_2023-11-08_2_Channel.C_019_Unit 2           1400         1500
311  Unknown_2023-11-08_3_Channel.C_015_Unit 1            800          900
310  Unknown_2023-11-08_3_Channel.C_015_Unit 1            200          400

[523 rows x 3 columns]

In [23]:
si_sorted_windows = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/si_sorted_Zombies_response_windows.pkl')
original_windows = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_response_windows.pkl')
si_sorted_windows.shape

(523, 3)

In [24]:
original_windows.shape

(735, 3)

In [25]:
marine = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_windows_KW_passed.pkl')
marine2 = pd.read_pickle('/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/sorted_Zombies_significant_windows_pKW_passed.pkl')

marine.shape

(39, 5)

In [26]:
marine2.shape

(6, 5)