In [15]:
from analyses.single_neuron_analysis import run_multi_predictor_glm
from analyses.spike_count import get_binned_spike_trials, aggregate_trial_level, extract_spike_counts_from_cells
import pandas as pd
import matplotlib
import seaborn as sns
import matplotlib.pyplot as plt
# date = '2023-09-26'
# round_no = 1
# analysis_df = prepare_binned_spike_data(date, round_no, 0.05)
# spike_df = aggregate_trial_level(analysis_df)

sig_neurons = pd.read_pickle(f'/home/connorlab/Documents/GitHub/Julie/Cortana/analysis_cache/Zombies_significant_neurons_pANOVAorGLM_passed.pkl')
neuron_df = extract_spike_counts_from_cells(sig_neurons)
neuron_df

Extracting spike counts: 100%|██████████| 319/319 [00:00<00:00, 522.45it/s]

,NeuronID,MonkeyName,MonkeyGroup,TaskField,SpikeCount
0,AMG_2023-09-26_1_Channel.C_014_Unit 1,114J,Instigators,1695747327712000,146
1,AMG_2023-09-26_1_Channel.C_014_Unit 1,69X,Zombies,1695747327797000,105
2,AMG_2023-09-26_1_Channel.C_014_Unit 1,59E,Instigators,1695747327892000,92
3,AMG_2023-09-26_1_Channel.C_014_Unit 1,40J,Stranger Things,1695747327973000,91
4,AMG_2023-09-26_1_Channel.C_014_Unit 1,40J,Stranger Things,1695747328008000,87
...,...,...,...,...,...
116210,Unknown_2023-12-18_3_Channel.C_029_Unit 1,40J,Stranger Things,1702937483729000,17
116211,Unknown_2023-12-18_3_Channel.C_029_Unit 1,G701,Best Frans,1702937494561000,11
116212,Unknown_2023-12-18_3_Channel.C_029_Unit 1,42Z,Instigators,1702937494973000,8
116213,Unknown_2023-12-18_3_Channel.C_029_Unit 1,35Y,Instigators,1702937495986000,10
116214,Unknown_2023-12-18_3_Channel.C_029_Unit 1,14F,Best Frans,1702937497230000,11

In [24]:
formula = """
SpikeCount ~ AffiliationFrom_z + AffiliationTo_z +
              AgonismFrom_z + AgonismTo_z +
              SubmissionFrom_z + SubmissionTo_z
"""

# formula = """
# SpikeCount ~ Rank + C(Sex) + C(Family) + C(Grouping)
# """

In [25]:
behavior_df= pd.read_excel('/home/connorlab/Documents/GitHub/Julie/social_data/zombies_social_data/zombies_marginals_without_cortana.xlsx')

In [26]:
from scipy.stats import zscore

for col in ['AffiliationFrom', 'AffiliationTo', 'AgonismFrom', 'AgonismTo', 'SubmissionFrom', 'SubmissionTo', ]:
    behavior_df[col + "_z"] = zscore(behavior_df[col])

In [27]:
# formula = "SpikeCount ~ PC1 + PC2"

In [28]:
# df = spike_df.merge(behavior_df, on="MonkeyName")
df = neuron_df.merge(behavior_df, on="MonkeyName")

In [29]:
significant, real_sig = run_multi_predictor_glm(df, formula, neuron_col="NeuronID")

Running multi-GLM per neuron: 100%|██████████| 319/319 [00:02<00:00, 131.66it/s]

In [34]:
# er_df = significant[significant['NeuronID'].str.startswith('ER')].copy()
# amg_df = significant[significant['NeuronID'].str.startswith('AMG')].copy()
top_neurons = (
    significant
    .sort_values(by='P>|z|')                # p-value 오름차순
    .groupby('NeuronID')                    # 뉴런 단위로
    .first()                                # 가장 작은 p값만 대표로 사용
    .sort_values(by='P>|z|')                # 다시 정렬
    .head(50)                               # 상위 50개 선택
    .index                                  # NeuronID만 추출
)
# reshape for heatmap
# heatmap_er_df = significant.pivot(index='NeuronID', columns='index', values='Coef.')

# Step 2: 해당 뉴런만 필터링해서 heatmap용 pivot 테이블 만들기
subset = significant[significant['NeuronID'].isin(top_neurons)]
heatmap_subset = subset.pivot(index='NeuronID', columns='index', values='Coef.')

plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_subset, cmap='coolwarm', center=0, fmt=".2f")
plt.title("Significant GLM Coefficients per Neuron")
plt.xlabel("Variable")
plt.ylabel("NeuronID")
plt.tight_layout()
plt.show()

In [37]:
heatmap_subset

index,AffiliationFrom_z,AffiliationTo_z,AgonismFrom_z,AgonismTo_z,Intercept,SubmissionFrom_z,SubmissionTo_z
NeuronID,,,,,,,
AMG_2023-09-26_1_Channel.C_014_Unit 1,-0.588625,0.544117,-0.207608,-0.073234,4.610375,0.001568,0.388974
AMG_2023-09-26_1_Channel.C_027_Unit 1,-5.035687,4.360550,0.038281,-1.179072,4.301139,0.727461,1.581616
AMG_2023-09-26_3_Channel.C_027_Unit 2,2.052582,-1.764349,-0.057081,0.524309,3.854155,-0.311068,-0.593667
AMG_2023-09-28_1_Channel.C_025_Unit 1,-3.018075,2.569669,-0.128425,-0.698986,4.302077,0.348959,1.166028
AMG_2023-09-29_3_Channel.C_025,1.287974,-1.118208,-0.089207,0.340335,3.735434,-0.194995,-0.447870
AMG_2023-10-03_1_Channel.C_009,8.767904,-7.532808,-0.327855,2.284223,3.931707,-1.281877,-2.266330
AMG_2023-10-03_1_Channel.C_019,-17.816593,15.357698,0.323189,-4.158001,5.663805,2.196550,4.960511
AMG_2023-10-03_1_Channel.C_028,-39.082435,33.396560,0.967802,-9.548053,6.902627,5.028296,10.490192
AMG_2023-10-03_3_Channel.C_004,-6.943351,5.950034,0.123119,-1.573305,4.119807,0.830135,1.931766
AMG_2023-10-03_3_Channel.C_012,1.537671,-1.286630,-0.030461,0.342470,4.050428,-0.181241,-0.425203
AMG_2023-10-03_4_Channel.C_004,-7.364052,6.383774,0.034960,-1.829437,4.417331,0.998039,2.182643
AMG_2023-10-03_4_Channel.C_012,0.016916,0.036684,-0.051008,-0.039323,4.108557,0.063245,-0.000245
AMG_2023-10-03_4_Channel.C_024,4.707050,-3.917073,-0.171383,1.206778,3.534808,-0.822353,-1.093838
AMG_2023-10-03_4_Channel.C_027,-1.812038,1.673577,-0.199859,-0.415515,4.739612,0.209163,0.868831
AMG_2023-10-04_1_Channel.C_028,-3.202364,2.801966,0.099578,-0.695887,4.681542,0.389714,0.830529
AMG_2023-10-04_2_Channel.C_020_Unit 1,2.017876,-1.791871,-0.003104,0.386282,4.533405,-0.136567,-0.563157
AMG_2023-10-04_2_Channel.C_029_Unit 1,-0.307715,0.311566,0.012514,-0.017550,4.207429,0.097505,0.158327
AMG_2023-10-04_3_Channel.C_009_Unit 1,3.218043,-2.723829,-0.172877,0.714895,4.051316,-0.374733,-0.796871
AMG_2023-10-04_4_Channel.C_006,-1.269258,1.111020,0.116112,-0.234719,4.556226,0.156988,0.230958
AMG_2023-10-04_4_Channel.C_021_Unit 1,-1.539204,1.354660,0.097735,-0.291612,4.537745,0.183203,0.330399
AMG_2023-10-04_4_Channel.C_022_Unit 2,0.502470,-0.411832,0.011066,0.077400,4.046233,-0.061324,-0.111259
AMG_2023-10-04_4_Channel.C_025_Unit 1,-1.168430,1.009450,0.053657,-0.235157,4.639815,0.147173,0.276365
AMG_2023-10-04_4_Channel.C_025_Unit 3,-1.523184,1.278056,-0.014609,-0.346437,3.940574,0.199183,0.524728
AMG_2023-10-04_4_Channel.C_027_Unit 2,-0.064783,0.088485,-0.005436,0.030205,3.651971,-0.001903,0.099514
AMG_2023-10-10_2_Channel.C_022,-6.847086,5.855886,0.069559,-1.588986,5.155255,0.953318,2.027381
AMG_2023-10-11_2_Channel.C_011,-4.059039,3.519557,-0.019547,-0.966403,4.003721,0.542841,1.320668
AMG_2023-10-11_2_Channel.C_020,-3.561779,3.127606,0.036339,-0.886383,4.102615,0.407918,0.966498
AMG_2023-10-11_2_Channel.C_021,-7.576928,6.517136,0.241602,-1.774248,4.444445,0.967183,1.990502
ER_2023-10-27_3_Channel.C_015,0.734669,-0.548380,-0.076653,0.170207,3.792121,-0.059816,-0.201573
ER_2023-10-27_3_Channel.C_016,-4.467995,3.903823,-0.025838,-1.052133,4.355773,0.556395,1.344321
ER_2023-10-27_3_Channel.C_026,1.174899,-0.966207,-0.142523,0.314589,4.370304,-0.104484,-0.041189
ER_2023-10-27_4_Channel.C_011,-3.909077,3.274185,0.201583,-0.959982,5.022586,0.495129,0.999187
ER_2023-10-27_4_Channel.C_016,0.641181,-0.519508,0.057197,0.203113,3.851244,-0.091117,-0.342260
ER_2023-10-27_4_Channel.C_020,-2.278885,1.866115,0.187243,-0.575558,4.737993,0.292934,0.526796
ER_2023-11-20_1_Channel.C_029,5.629676,-4.801918,-0.121086,1.435590,3.783111,-0.825358,-1.651115
ER_2023-11-20_1_Channel.C_031,10.889123,-9.229870,-0.078039,2.728231,2.865315,-1.594063,-3.246819
ER_2023-11-22_3_Channel.C_022,-1.637418,1.403918,0.058662,-0.349412,3.903827,0.184926,0.387343
ER_2023-11-22_4_Channel.C_003,4.246241,-3.665406,-0.213082,1.052774,3.435126,-0.583841,-0.986801
ER_2023-11-22_4_Channel.C_024,-5.249926,4.470040,-0.039240,-1.225700,4.094804,0.656892,1.685463
ER_2023-11-25_1_Channel.C_028,-5.940532,5.054522,0.323019,-1.392657,4.382002,0.814120,1.353217
ER_2023-11-27_2_Channel.C_024,-1.090520,0.919077,-0.078022,-0.317522,3.875702,0.176589,0.448148
ER_2023-11-27_3_Channel.C_014,-7.501376,6.423942,0.204724,-1.781990,4.478374,0.967370,2.075289
ER_2023-11-28_3_Channel.C_027,-10.006444,8.570237,0.259098,-2.511390,4.497423,1.379762,2.786662
ER_2023-11-28_3_Channel.C_028,-6.912829,5.911111,0.070182,-1.702360,4.204609,0.956823,2.067459
ER_2023-11-28_4_Channel.C_027,-7.359859,6.344922,0.193254,-1.789559,4.705252,0.953341,1.926345
ER_2023-12-05_4_Channel.C_008,-9.333516,7.992805,0.549591,-2.185154,4.725109,1.097549,2.071068
ER_2023-12-05_4_Channel.C_025,-6.121118,5.432270,0.236082,-1.383109,4.531491,0.685278,1.098052
ER_2023-12-14_1_Channel.C_018,2.867593,-2.473917,-0.292059,0.758823,5.137431,-0.300092,-0.300541
ER_2023-12-14_2_Channel.C_012,-2.776369,2.401853,0.040760,-0.627593,3.930673,0.348496,0.853826
ER_2023-12-14_4_Channel.C_008,-14.462703,12.492343,0.924783,-3.520592,4.928612,1.913691,3.040864

In [36]:
# reshape for heatmap
heatmap_amg_df = amg_df.pivot(index='NeuronID', columns='index', values='Coef.')

plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_amg_df, cmap='coolwarm', center=0, fmt=".2f")
plt.title("Significant GLM Coefficients per Neuron in AMG")
plt.xlabel("Variable")
plt.ylabel("NeuronID")
plt.tight_layout()
plt.show()

KeyboardInterrupt:

In [21]:
amg_sig_count = amg_df['index'].value_counts().sort_index()

plt.figure(figsize=(10, 4))
sns.barplot(x=amg_sig_count.index, y=amg_sig_count.values)
plt.ylabel("Number of Significant Neurons")
plt.title("Which Variables Drive Neural Firing in AMG?")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [22]:
er_sig_count = er_df['index'].value_counts().sort_index()

plt.figure(figsize=(10, 4))
sns.barplot(x=er_sig_count.index, y=er_sig_count.values)
plt.ylabel("Number of Significant Neurons")
plt.title("Which Variables Drive Neural Firing in ER?")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()